'use client'
import { useMemo, useState } from 'react'

type Tool={name:string;desc:string;action:string;kind:string}
const make=(a:string[][]):Tool[]=>a.map(([name,desc,action,kind])=>({name,desc,action,kind}))
const pdf=make([
['Merge PDF','Combine multiple PDFs into one file','merge-pdf','PDF'],['Split PDF','Create a first-page split file','split-first-page','PDF'],['Rotate PDF','Rotate every page by 90°','rotate-pdf','PDF'],['Delete PDF Pages','Remove the first page','delete-first-page','PDF'],['Extract PDF Pages','Extract the first two pages','extract-pages','PDF'],['Add Watermark','Stamp ARK watermark on every page','watermark','PDF'],['Page Numbers','Add page numbers to every page','page-numbers','PDF'],['PDF Metadata','Export basic PDF metadata as JSON','metadata','PDF'],
['Compress PDF','Reduce PDF size with qpdf worker','compress-pdf','PDF'],['PDF to JPG','Render every PDF page as JPG','pdf-to-jpg','PDF'],['PDF to PNG','Render every PDF page as PNG','pdf-to-png','PDF'],['JPG to PDF','Create a PDF from one or more JPG images','jpg-to-pdf','PDF'],['PNG to PDF','Create a PDF from one or more PNG images','png-to-pdf','PDF'],['PDF to Text','Extract selectable text','pdf-to-text','PDF'],['PDF to Word','Convert PDF text into DOCX','pdf-to-word','PDF'],['Word to PDF','Convert DOCX using LibreOffice','word-to-pdf','PDF'],['PPT to PDF','Convert presentations using LibreOffice','ppt-to-pdf','PDF'],['Excel to PDF','Convert spreadsheets using LibreOffice','excel-to-pdf','PDF'],['HTML to PDF','Render HTML as a PDF','html-to-pdf','PDF'],['Sign PDF','Add a text signature to every page','sign-pdf','PDF']])
const image=make([['JPG to PNG','Convert JPG to PNG','png','Image'],['PNG to JPG','Convert PNG to JPG','jpg','Image'],['WEBP to JPG','Convert WEBP to JPG','jpg','Image'],['JPG to WEBP','Convert JPG to WEBP','webp','Image'],['PNG to WEBP','Convert PNG to WEBP','webp','Image'],['Image Compress','Compress to WebP with adjustable quality','compress','Image'],['Image Resize','Resize without enlarging','resize','Image'],['Image Crop','Crop to exact pixel dimensions','crop','Image']])
const media=make([['MP3 to WAV','FFmpeg audio conversion','mp3-to-wav','Audio'],['WAV to MP3','FFmpeg audio conversion','wav-to-mp3','Audio'],['MP3 to OGG','FFmpeg audio conversion','mp3-to-ogg','Audio'],['Audio Compress','FFmpeg audio compression','audio-compress','Audio'],['MP4 to WEBM','FFmpeg video conversion','mp4-to-webm','Video'],['WEBM to MP4','FFmpeg video conversion','webm-to-mp4','Video'],['MP4 to GIF','FFmpeg GIF creation','mp4-to-gif','Video'],['Video Compress','FFmpeg video compression','video-compress','Video'],['Video Trim','FFmpeg video trimming','video-trim','Video'],['Video to MP3','Extract audio with FFmpeg','video-to-mp3','Video']])
const other=make([['DOCX to TXT','Extract Word text','docx-to-txt','Office'],['TXT to PDF','Create PDF from text','txt-to-pdf','Office'],['CSV to XLSX','Spreadsheet conversion','csv-to-xlsx','Office'],['XLSX to CSV','Spreadsheet conversion','xlsx-to-csv','Office'],['PPTX to Images','Render slides to PNG','pptx-to-images','Office'],['Bank Statement Extractor','Extract text, dates, amounts and account fields','bank-statement-tools','Finance'],['Electricity Bill Extractor','Extract bill text, dates, amounts and units','electricity-bill-tools','Utilities'],['Food & Nutrition Extractor','Extract nutrition values from food documents','food-nutrition-files','Food'],['Invoice Extractor','Extract invoice text, dates and amounts','invoice-tools','Finance']])
const sections=[['pdf','PDF tools',pdf],['images','Image conversion',image],['media','Audio & video',media],['files','Other file conversions',other]] as const
const workerActions=new Set(pdf.map(t=>t.action).concat(media.map(t=>t.action),other.map(t=>t.action)))

function Card({t,onOpen}:{t:Tool;onOpen:(t:Tool)=>void}){return <button className="card" onClick={()=>onOpen(t)}><div className="icon">{t.kind==='PDF'?'PDF':t.kind==='Image'?'IMG':t.kind==='Audio'?'AUD':t.kind==='Video'?'VID':'FILE'}</div><h3>{t.name}</h3><p>{t.desc}</p><span className="badge">Ready</span></button>}

export default function Home(){
 const [active,setActive]=useState<Tool|null>(null); const [files,setFiles]=useState<File[]>([]); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [query,setQuery]=useState('');
 const [signature,setSignature]=useState(''); const [width,setWidth]=useState(''); const [height,setHeight]=useState(''); const [left,setLeft]=useState('0'); const [top,setTop]=useState('0'); const [quality,setQuality]=useState('82'); const [html,setHtml]=useState(''); const [start,setStart]=useState('00:00:00'); const [duration,setDuration]=useState('00:00:10');
 const all=sections.flatMap(x=>x[2]); const filtered=useMemo(()=>all.filter(t=>(t.name+' '+t.desc+' '+t.kind).toLowerCase().includes(query.toLowerCase())),[query]);
 function openTool(t:Tool){setActive(t);setFiles([]);setMessage('');setSignature('');setWidth('');setHeight('');setLeft('0');setTop('0');setQuality('82');setHtml('');setStart('00:00:00');setDuration('00:00:10')}
 function accept(){if(!active)return undefined;if(active.action==='merge-pdf')return '.pdf';if(active.action==='jpg-to-pdf')return 'image/jpeg';if(active.action==='png-to-pdf')return 'image/png';if(active.action==='docx-to-txt')return '.docx';if(active.action==='txt-to-pdf')return '.txt';if(active.action==='csv-to-xlsx')return '.csv';if(active.action==='xlsx-to-csv')return '.xlsx';if(active.action==='pdf-to-word')return '.pdf';if(active.action==='word-to-pdf')return '.docx';if(active.action==='ppt-to-pdf'||active.action==='pptx-to-images')return '.pptx';if(active.action==='excel-to-pdf')return '.xlsx,.xls';if(['pdf-to-jpg','pdf-to-png','compress-pdf','pdf-to-text','bank-statement-tools','electricity-bill-tools','food-nutrition-files','invoice-tools'].includes(active.action))return '.pdf,.txt,.csv';if(active.action==='video-trim')return 'video/*';if(active.kind==='Image')return 'image/*';if(active.kind==='Audio')return 'audio/*';if(active.kind==='Video')return 'video/*';return '.pdf'}
 async function process(){
  if(!active)return; if(!files.length&&active.action!=='html-to-pdf')return setMessage('Choose a file first.'); if(active.action==='html-to-pdf'&&!html.trim())return setMessage('Enter HTML first.');
  setBusy(true);setMessage(workerActions.has(active.action)?'Processing with the ARK engine…':'Processing on the ARK server…');
  try{const fd=new FormData();fd.append('action',active.action);files.forEach(f=>fd.append('files',f));if(active.action==='sign-pdf')fd.append('signature',signature);if(active.action==='html-to-pdf')fd.append('html',html);if(active.action==='video-trim'){fd.append('start',start);fd.append('duration',duration)}const r=await fetch('/api/process',{method:'POST',body:fd});if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j.error||'Processing failed');}const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=active.action==='metadata'?'pdf-metadata.json':active.action==='docx-to-txt'?'document.txt':active.action==='csv-to-xlsx'?'converted.xlsx':active.action==='xlsx-to-csv'?'converted.csv':active.action==='pdf-to-text'?'document.txt':active.action==='pdf-to-word'?'document.docx':active.action==='pdf-to-jpg'||active.action==='pdf-to-png'?'pdf-pages.zip':active.action==='word-to-pdf'||active.action==='ppt-to-pdf'||active.action==='excel-to-pdf'?'converted.pdf':active.action.endsWith('-tools')||active.action==='food-nutrition-files'||active.action==='invoice-tools'?active.action+'.json':active.action+'.bin';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Done — your processed file is downloading.')}catch(e){setMessage(e instanceof Error?e.message:'Processing failed.')}finally{setBusy(false)}
 }
 async function imageProcess(){if(!active||!files[0])return setMessage('Choose an image first.');setBusy(true);setMessage('Processing image with Sharp…');try{const fd=new FormData();fd.append('file',files[0]);fd.append('format',active.action);fd.append('quality',quality);if(width)fd.append('width',width);if(height)fd.append('height',height);fd.append('left',left);fd.append('top',top);const r=await fetch('/api/image',{method:'POST',body:fd});if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j.error||'Image processing failed')}const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;const ext=active.action==='jpg'?'jpg':active.action==='png'?'png':'webp';a.download='ark-'+active.action+'.'+ext;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Done — image processed.')}catch(e){setMessage(e instanceof Error?e.message:'Image processing failed.')}finally{setBusy(false)}}
 const run=active?.kind==='Image'&&active.action!=='coming'?imageProcess:process;
 return <><header className="nav"><div className="wrap navInner"><div className="brand">PDF & File Tools <span>ARK</span></div><nav className="navlinks"><a href="#pdf">PDF</a><a href="#images">Images</a><a href="#media">Audio & Video</a><a href="#files">Files</a></nav></div></header><main>
 <section className="hero"><div className="wrap"><span className="eyebrow">FULL-STACK FILE WORKSPACE</span><h1>Powerful file tools.<br/><span>Simple to understand.</span></h1><p>PDF comes first. Lightweight jobs run in Next.js; heavy PDF, Office, HTML and media jobs are routed to the dedicated ARK processing worker.</p><div className="heroAction"><a className="primary" href="#pdf">Start with PDF ↓</a></div></div></section>
 {active&&<section className="section toolSection"><div className="wrap"><div className="drop"><div className="toolTitle"><div><strong>{active.name}</strong><small>{active.desc}</small></div><button className="close" onClick={()=>{setActive(null);setFiles([]);setMessage('')}}>×</button></div>
 {active.action==='sign-pdf'&&<input className="toolInput" value={signature} onChange={e=>setSignature(e.target.value)} placeholder="Signature name / text" />}
 {active.action==='html-to-pdf'&&<textarea className="toolInput" value={html} onChange={e=>setHtml(e.target.value)} placeholder="Paste HTML here…" rows={8}/>} 
 {active.action==='video-trim'&&<div className="fields"><input className="toolInput" value={start} onChange={e=>setStart(e.target.value)} placeholder="Start e.g. 00:00:05"/><input className="toolInput" value={duration} onChange={e=>setDuration(e.target.value)} placeholder="Duration e.g. 00:00:10"/></div>}
 {active.action==='resize'&&<div className="fields"><input className="toolInput" inputMode="numeric" value={width} onChange={e=>setWidth(e.target.value)} placeholder="Width (px)"/><input className="toolInput" inputMode="numeric" value={height} onChange={e=>setHeight(e.target.value)} placeholder="Height (px, optional)"/></div>}
 {active.action==='crop'&&<div className="fields"><input className="toolInput" inputMode="numeric" value={width} onChange={e=>setWidth(e.target.value)} placeholder="Crop width (px)"/><input className="toolInput" inputMode="numeric" value={height} onChange={e=>setHeight(e.target.value)} placeholder="Crop height (px)"/><input className="toolInput" inputMode="numeric" value={left} onChange={e=>setLeft(e.target.value)} placeholder="Left (px)"/><input className="toolInput" inputMode="numeric" value={top} onChange={e=>setTop(e.target.value)} placeholder="Top (px)"/></div>}
 {active.kind==='Image'&&(active.action==='compress'||active.action==='resize'||active.action==='crop')&&<label className="quality">Quality: {quality}<input type="range" min="10" max="100" value={quality} onChange={e=>setQuality(e.target.value)}/></label>}
 {active.action!=='html-to-pdf'&&<label className="primary chooser"><input type="file" accept={accept()} multiple={active.action==='merge-pdf'||active.action==='jpg-to-pdf'||active.action==='png-to-pdf'} onChange={e=>setFiles(Array.from(e.target.files||[]))}/>{files.length?`${files.length} file(s) selected`:'Choose file(s)'}</label>}
 {files.length>0&&<div className="files">{files.map(f=><div key={f.name}>{f.name} · {(f.size/1024/1024).toFixed(2)} MB</div>)}</div>}<button className="primary process" disabled={busy||(!files.length&&active.action!=='html-to-pdf')||(active.action==='sign-pdf'&&!signature.trim())} onClick={run}>{busy?'Processing…':'Process with ARK'}</button>{message&&<div className="result">{message}</div>}</div></div></section>}
 {sections.map(([id,title,list])=><section className="section" id={id} key={id}><div className="wrap"><div className="sectionHead"><div><h2>{title}</h2><p>{id==='pdf'?'Core PDF operations first.':id==='images'?'Fast image format conversion and utilities.':id==='media'?'FFmpeg-powered media layer runs in the backend worker.':'Office, finance, utility, food and document workflows.'}</p></div><span className="count">{list.length} tools</span></div><div className="grid">{list.map(t=><Card key={t.name} t={t} onOpen={openTool}/>)}</div></div></section>)}
 <section className="section"><div className="wrap searchBox"><h2>Find any tool</h2><p>Search across the complete toolbox.</p><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search merge, JPG, Word, bank, invoice…"/>{query&&<div className="grid searchGrid">{filtered.map(t=><Card key={t.name} t={t} onOpen={openTool}/>)}</div>}</div></section>
 </main><footer className="footer">PDF & File Tools ARK · Full-stack architecture · Heavy processing via dedicated worker.</footer></>}
