'use client'
import { useMemo, useState } from 'react'

type Tool={name:string;desc:string;action:string;kind:string}
const make=(a:string[][]):Tool[]=>a.map(([name,desc,action,kind])=>({name,desc,action,kind}))
const pdf=make([
['Merge PDF','Combine multiple PDFs into one file','merge-pdf','PDF'],['Split PDF','Create a first-page split file','split-first-page','PDF'],['Rotate PDF','Rotate every page by 90°','rotate-pdf','PDF'],['Delete PDF Pages','Remove the first page','delete-first-page','PDF'],['Extract PDF Pages','Extract the first two pages','extract-pages','PDF'],['Add Watermark','Stamp ARK watermark on every page','watermark','PDF'],['Page Numbers','Add page numbers to every page','page-numbers','PDF'],['PDF Metadata','Export basic PDF metadata as JSON','metadata','PDF'],
['Compress PDF','Reduce PDF size with server processing','coming','PDF'],['PDF to JPG','Render pages to JPG','coming','PDF'],['PDF to PNG','Render pages to PNG','coming','PDF'],['JPG to PDF','Create PDF from JPG images','coming','PDF'],['PNG to PDF','Create PDF from PNG images','coming','PDF'],['PDF to Text','Extract selectable text','coming','PDF'],['PDF to Word','Convert PDF content to DOCX','coming','PDF'],['Word to PDF','Convert DOCX using Office engine','coming','PDF'],['PPT to PDF','Convert presentations','coming','PDF'],['Excel to PDF','Convert spreadsheets','coming','PDF'],['HTML to PDF','Render HTML as PDF','coming','PDF'],['Sign PDF','Add a signature','coming','PDF']])
const image=make([['JPG to PNG','Convert JPG to PNG','png','Image'],['PNG to JPG','Convert PNG to JPG','jpg','Image'],['WEBP to JPG','Convert WEBP to JPG','jpg','Image'],['JPG to WEBP','Convert JPG to WEBP','webp','Image'],['PNG to WEBP','Convert PNG to WEBP','webp','Image'],['Image Compress','Compress an image','webp','Image'],['Image Resize','Resize images','coming','Image'],['Image Crop','Crop images','coming','Image']])
const media=make([['MP3 to WAV','FFmpeg audio conversion','coming','Audio'],['WAV to MP3','FFmpeg audio conversion','coming','Audio'],['MP3 to OGG','FFmpeg audio conversion','coming','Audio'],['Audio Compress','FFmpeg audio compression','coming','Audio'],['MP4 to WEBM','FFmpeg video conversion','coming','Video'],['WEBM to MP4','FFmpeg video conversion','coming','Video'],['MP4 to GIF','FFmpeg GIF creation','coming','Video'],['Video Compress','FFmpeg video compression','coming','Video'],['Video Trim','FFmpeg video trimming','coming','Video'],['Video to MP3','Extract audio with FFmpeg','coming','Video']])
const other=make([['DOCX to TXT','Extract Word text','coming','Office'],['TXT to PDF','Create PDF from text','coming','Office'],['CSV to XLSX','Spreadsheet conversion','coming','Office'],['XLSX to CSV','Spreadsheet conversion','coming','Office'],['PPTX to Images','Render slides','coming','Office'],['Bank Statement Tools','Finance document workflow','coming','Finance'],['Electricity Bill Tools','Utility document workflow','coming','Utilities'],['Food & Nutrition Files','Nutrition document workflow','coming','Food'],['Invoice Tools','Invoice extraction workflow','coming','Finance']])
const sections=[['pdf','PDF tools',pdf],['images','Image conversion',image],['media','Audio & video',media],['files','Other file conversions',other]] as const

function Card({t,onOpen}:{t:Tool;onOpen:(t:Tool)=>void}){return <button className="card" onClick={()=>onOpen(t)}><div className="icon">{t.kind==='PDF'?'PDF':t.kind==='Image'?'IMG':t.kind==='Audio'?'AUD':t.kind==='Video'?'VID':'FILE'}</div><h3>{t.name}</h3><p>{t.desc}</p><span className={t.action==='coming'?'badge muted':'badge'}>{t.action==='coming'?'Engine next':'Ready'}</span></button>}

export default function Home(){
 const [active,setActive]=useState<Tool|null>(null); const [files,setFiles]=useState<File[]>([]); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [query,setQuery]=useState('');
 const all=sections.flatMap(x=>x[2]); const filtered=useMemo(()=>all.filter(t=>(t.name+' '+t.desc+' '+t.kind).toLowerCase().includes(query.toLowerCase())),[query]);
 async function process(){
  if(!active||!files.length)return setMessage('Choose a file first.');
  if(active.action==='coming')return setMessage('This tool is registered. Its dedicated processing engine will be connected next — no fake conversion.');
  setBusy(true);setMessage('Processing on the ARK server…');
  try{const fd=new FormData();fd.append('action',active.action);files.forEach(f=>fd.append('files',f));const r=await fetch('/api/process',{method:'POST',body:fd});if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j.error||'Processing failed');}const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=active.name.toLowerCase().replaceAll(' ','-')+(active.action==='metadata'?'.json':'.pdf');a.click();URL.revokeObjectURL(url);setMessage('Done — your processed file is downloading.')}catch(e){setMessage(e instanceof Error?e.message:'Processing failed.')}finally{setBusy(false)}
 }
 async function imageProcess(){if(!active||!files[0])return setMessage('Choose an image first.');setBusy(true);setMessage('Processing image with Sharp…');try{const fd=new FormData();fd.append('file',files[0]);fd.append('format',active.action);const r=await fetch('/api/image',{method:'POST',body:fd});if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j.error||'Image processing failed')}const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='ark-converted.'+(active.action==='jpg'?'jpg':active.action);a.click();URL.revokeObjectURL(url);setMessage('Done — image converted.')}catch(e){setMessage(e instanceof Error?e.message:'Image processing failed.')}finally{setBusy(false)}}
 const run=active?.kind==='Image'&&active.action!=='coming'?imageProcess:process;
 return <><header className="nav"><div className="wrap navInner"><div className="brand">PDF & File Tools <span>ARK</span></div><nav className="navlinks"><a href="#pdf">PDF</a><a href="#images">Images</a><a href="#media">Audio & Video</a><a href="#files">Files</a></nav></div></header><main>
 <section className="hero"><div className="wrap"><span className="eyebrow">FULL-STACK FILE WORKSPACE</span><h1>Powerful file tools.<br/><span>Simple to understand.</span></h1><p>PDF comes first. Scroll for image, audio, video, office and category-specific tools. Lightweight jobs run directly through the web app; heavy jobs use dedicated processing engines.</p><div className="heroAction"><a className="primary" href="#pdf">Start with PDF ↓</a></div></div></section>
 {active&&<section className="section toolSection"><div className="wrap"><div className="drop"><div className="toolTitle"><div><strong>{active.name}</strong><small>{active.desc}</small></div><button className="close" onClick={()=>{setActive(null);setFiles([]);setMessage('')}}>×</button></div><label className="primary chooser"><input type="file" multiple onChange={e=>setFiles(Array.from(e.target.files||[]))}/>{files.length?`${files.length} file(s) selected`:'Choose file(s)'}</label>{files.length>0&&<div className="files">{files.map(f=><div key={f.name}>{f.name} · {(f.size/1024/1024).toFixed(2)} MB</div>)}</div>}<button className="primary process" disabled={busy||!files.length} onClick={run}>{busy?'Processing…':'Process with ARK'}</button>{message&&<div className="result">{message}</div>}</div></div></section>}
 {sections.map(([id,title,list])=><section className="section" id={id} key={id}><div className="wrap"><div className="sectionHead"><div><h2>{title}</h2><p>{id==='pdf'?'Core PDF operations first.':id==='images'?'Fast image format conversion and utilities.':id==='media'?'FFmpeg-powered media layer is designed for the backend worker.':'Office, finance, utility, food and document workflows.'}</p></div><span className="count">{list.length} tools</span></div><div className="grid">{list.map(t=><Card key={t.name} t={t} onOpen={setActive}/>)}</div></div></section>)}
 <section className="section"><div className="wrap searchBox"><h2>Find any tool</h2><p>Search across the complete toolbox.</p><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search merge, JPG, Word, bank, invoice…"/>{query&&<div className="grid searchGrid">{filtered.map(t=><Card key={t.name} t={t} onOpen={setActive}/>)}</div>}</div></section>
 </main><footer className="footer">PDF & File Tools ARK · Full-stack architecture · No fake conversion buttons.</footer></>}
